[build]
  command = ""            # kein Build für OpenUI5
  publish = "webapp"      # relativ zum Base-Directory

[[redirects]]
  from = "/api/*"
  to = "https://dhc-buecherverwaltung.onrender.com/:splat"
  status = 200
  force = true
